/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toy.anagrams.ui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import packagestampa.FrameStampa;
import packagestampa.StampaFile;

/**
 *
 * @author Carmine
 */
public class panelRiga extends javax.swing.JPanel {

    /**
     * Creates new form panelRiga
     */
    public panelRiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setMaximumSize(new java.awt.Dimension(400, 36));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail_up.png"))); // NOI18N
        jButton1.setToolTipText("Invia Fattura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stampa.png"))); // NOI18N
        jButton2.setToolTipText("Stampa Fattura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jButton3.setToolTipText("Elimina Fattura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        jButton4.setToolTipText("Visualizza Fattura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String  workingDir= System.getProperty("user.home");
         String split[]=this.jLabel1.getText().split("_");
         String s= split[1].substring(0,10);
         new frameEmail(workingDir+"/Desktop/Fatture/_"+this.jLabel1.getText(),"",s).setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        if(this.jLabel1.getText().equals("")){
             JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Attenzione non è specificato nessun file");
                return;
        }
        else{
             String  workingDir= System.getProperty("user.home");
            if(Desktop.isDesktopSupported()){
            try{
                    File myFile=new File(workingDir+"/Desktop/Fatture/_"+this.jLabel1.getText());
                    Desktop.getDesktop().open(myFile);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Errore Apertura File , forse è già aperto" + e);
                return;
            }
                
            }
        
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(this.jLabel1.getText().equals("")){
            JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Non hai inserito nessun File!!");
            return;
        }
        else{
              String  workingDir= System.getProperty("user.home");
            try {
                StampaFile f=new StampaFile(workingDir+"/Desktop/Fatture/_"+this.jLabel1.getText());
                f.stampa();
            } catch (IOException ex) {
                Logger.getLogger(FrameStampa.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Non hai inserito nessun File!!");
                return;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         URL iconURL = getClass().getResource("/image/info.png");
         ImageIcon icon = new ImageIcon(iconURL);
         int result=  JOptionPane.showOptionDialog(null, 
         "Sei sicuro di voler eliminare la fattura? ", 
         "Info", 
         JOptionPane.YES_OPTION, 
         JOptionPane.NO_OPTION, 
         icon,
       
        new String[]{"Si", "No" }, // this is the array
        "default");
        if(JOptionPane.YES_OPTION==result){
           
              try{
                String  workingDir= System.getProperty("user.home");
    		File file = new File(workingDir+"/Desktop/Fatture/_"+this.jLabel1.getText());

    		if(file.delete()){
    			System.out.println(file.getName() + " is deleted!");
                        this.setVisible(false);
      
    		}else{
    			JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Errore Eliminazione File!!");
                return;
    		}

    	}catch(Exception e){
                e.printStackTrace();
    		JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(this), "Errore Eliminazione File!!" + e );
                return;

    	  }
            
         }
     
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(String jLabel1) {
        this.jLabel1.setText(jLabel1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
